version: "3.8"

services:
  api:
    container_name: aqua.wishlist.api
    build:
      context: .
      target: production
      dockerfile: Dockerfile

    restart: always

    environment:
      DATABASE_URL:
      JWT_SECRET:

    ports:
      - ${API_LISTEN:-8080}:8080

  postgresql:
    container_name: aqua.wishlist.postgresql
    image: postgres:14

    restart: always

    environment:
      POSTGRES_DB:
      POSTGRES_USER:
      POSTGRES_PASSWORD:

    volumes:
      - data-postgresql:/var/lib/postgresql/data

volumes:
  data-postgresql: {}
